# Библиотека NumPy
NumPy (NumericalPython) - это библиотека Python с открытым
исходным кодом, которая используется практически во всех областях науки
и техники. Это универсальный стандарт для работы с числовыми данными в
Python.
Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:
 pip install numpy
Чтобы начать использовать NumPy необходимо импортировать
соответствующую библиотеку:
 `import numpy as np`
Основным объектом NumPy является однородный многомерный
массив (в numpy называется numpy.ndarray). Это многомерный массив
элементов (обычно чисел), одного типа.
Наиболее важные атрибуты объектов ndarray:
- **ndarray.ndim** - число измерений (чаще их называют "оси") массива.
- **ndarray.shape** - размеры массива, его форма. Это кортеж натуральных
чисел, показывающий длину массива по каждой оси. Для матрицы из n строк
и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
- **ndarray.size** - количество элементов массива. Очевидно, равно
произведению всех элементов атрибута shape.
- **ndarray.dtype** - объект, описывающий тип элементов массива. Можно
определить dtype, используя стандартные типы данных Python. NumPy здесь
предоставляет целый букет возможностей, как встроенных, например: bool_,
character, int8, int16, int32, int64, float8, float16, float32, float64, complex64,
object_, так и возможность определить собственные типы данных, в том
числе и составные.
- **ndarray.itemsize** - размер каждого элемента массива в байтах.
- **ndarray.data** - буфер, содержащий фактические элементы массива.
Обычно не нужно использовать этот атрибут, так как обращаться к
элементам массива проще всего с помощью индексов.
Подробнее о массивах в NumPy можно найти в официальной
документации https://numpy.org/doc/stable/user/absolute_beginners.html

### 1.2.1 Пример

Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [5]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


### 1.2.2 Пример
Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [7]:
import numpy as np

a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)
d = np.arange(10,20)
print(a,"\n",b,"\n",c,"\n",d,"\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19] 



### 1.2.3 Пример
Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [8]:
X = np.random.random((10,10))
Xmin, Xmax, Xmean, = X.min(), X.max(), X.mean()
print(Xmin, Xmax, Xmean)

0.00433806990030472 0.9756037149839829 0.4627565445417157


### 1.2.4 Пример
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

In [9]:
K = np.arange(25).reshape(5,5)
K[[0,1]] = K[[1,0]]
print(K)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 1.2.5 Пример
Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [10]:
import numpy as np
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


### 1.2.6 Пример
Отсортировать массив.

In [11]:
import numpy as np
arr = np.array([2,8,5,4,1,3,7,6])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


### 1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [86]:
import numpy as np
size = 8
arr = np.full((size,size),0)
for line in arr[0:size:2]:
    line[np.mod(np.arange(0,size),2)!=0]=1
for line in arr[1:size:2]:
    line[np.mod(np.arange(size)+1,2)!=0]=1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

In [90]:
import numpy as np

sample = np.arange(5)
arr = np.full((5,5),sample)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 1.3.3 Задание
Создать массив 3x3x3 со случайными значениями

In [92]:
import numpy as np

arr = np.random.random((3,3,3))
print(arr)

[[[0.47921131 0.23006963 0.90365568]
  [0.27904662 0.78140358 0.460416  ]
  [0.26676811 0.74426371 0.24599734]]

 [[0.48896719 0.19472616 0.48567536]
  [0.5527851  0.92530965 0.60248458]
  [0.83500298 0.47415633 0.65414222]]

 [[0.4710312  0.49372073 0.57519482]
  [0.81664887 0.83572509 0.01822079]
  [0.05308503 0.21597604 0.42106337]]]


### 1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах.

In [106]:
import numpy as np

arr = np.full((10,10),1)
for line in arr[1:9:1]:
    line[1:9:1]=0
print(arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


### 1.3.5 Задание
Создайте массив и отсортируйте его по убыванию.

In [114]:
import numpy as np
arr = np.array([1,9,3,6,8,7,5,2,0,3,6,4,1])
print(-np.sort(-arr))

[9 8 7 6 6 5 4 3 3 2 1 1 0]


### 1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность.

In [119]:
import numpy as np

matr = np.array([[0,3,9,5,6],[3,6,8,9,0],[3,3,4,7,5]])
print(matr)
print("Size: ",matr.size)
print("Shape: ", matr.shape)
print("Dimension: ", matr.ndim)

[[0 3 9 5 6]
 [3 6 8 9 0]
 [3 3 4 7 5]]
Size:  15
Shape:  (3, 5)
Dimension:  2
