## 1. Библиотека NumPy
NumPy (NumericalPython) - это библиотека Python с открытым
исходным кодом, которая используется практически во всех областях науки
и техники. Это универсальный стандарт для работы с числовыми данными в
Python.
Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:
 pip install numpy
Чтобы начать использовать NumPy необходимо импортировать
соответствующую библиотеку:
 `import numpy as np`
Основным объектом NumPy является однородный многомерный
массив (в numpy называется numpy.ndarray). Это многомерный массив
элементов (обычно чисел), одного типа.
Наиболее важные атрибуты объектов ndarray:
- **ndarray.ndim** - число измерений (чаще их называют "оси") массива.
- **ndarray.shape** - размеры массива, его форма. Это кортеж натуральных
чисел, показывающий длину массива по каждой оси. Для матрицы из n строк
и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
- **ndarray.size** - количество элементов массива. Очевидно, равно
произведению всех элементов атрибута shape.
- **ndarray.dtype** - объект, описывающий тип элементов массива. Можно
определить dtype, используя стандартные типы данных Python. NumPy здесь
предоставляет целый букет возможностей, как встроенных, например: bool_,
character, int8, int16, int32, int64, float8, float16, float32, float64, complex64,
object_, так и возможность определить собственные типы данных, в том
числе и составные.
- **ndarray.itemsize** - размер каждого элемента массива в байтах.
- **ndarray.data** - буфер, содержащий фактические элементы массива.
Обычно не нужно использовать этот атрибут, так как обращаться к
элементам массива проще всего с помощью индексов.
Подробнее о массивах в NumPy можно найти в официальной
документации https://numpy.org/doc/stable/user/absolute_beginners.html

### 1.2.1 Пример

Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [120]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


### 1.2.2 Пример
Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [121]:
import numpy as np

a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)
d = np.arange(10,20)
print(a,"\n",b,"\n",c,"\n",d,"\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19] 



### 1.2.3 Пример
Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [122]:
X = np.random.random((10,10))
Xmin, Xmax, Xmean, = X.min(), X.max(), X.mean()
print(Xmin, Xmax, Xmean)

0.0052124614255441015 0.9981625253452142 0.519148224294276


### 1.2.4 Пример
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

In [123]:
K = np.arange(25).reshape(5,5)
K[[0,1]] = K[[1,0]]
print(K)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 1.2.5 Пример
Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [124]:
import numpy as np
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


### 1.2.6 Пример
Отсортировать массив.

In [125]:
import numpy as np
arr = np.array([2,8,5,4,1,3,7,6])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


### 1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [126]:
import numpy as np
size = 8
arr = np.full((size,size),0)
for line in arr[0:size:2]:
    line[np.mod(np.arange(0,size),2)!=0]=1
for line in arr[1:size:2]:
    line[np.mod(np.arange(size)+1,2)!=0]=1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

In [127]:
import numpy as np

sample = np.arange(5)
arr = np.full((5,5),sample)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 1.3.3 Задание
Создать массив 3x3x3 со случайными значениями

In [128]:
import numpy as np

arr = np.random.random((3,3,3))
print(arr)

[[[0.91820008 0.43183395 0.17969513]
  [0.08390997 0.27768207 0.07753908]
  [0.44810821 0.34271119 0.97324823]]

 [[0.3592834  0.20775208 0.57178481]
  [0.98700606 0.81974544 0.46699005]
  [0.40226835 0.05353945 0.15495859]]

 [[0.99963002 0.22664852 0.87966298]
  [0.68720171 0.14540512 0.91230987]
  [0.73501839 0.94944466 0.14859732]]]


### 1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах.

In [129]:
import numpy as np

arr = np.full((10,10),1)
for line in arr[1:9:1]:
    line[1:9:1]=0
print(arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


### 1.3.5 Задание
Создайте массив и отсортируйте его по убыванию.

In [130]:
import numpy as np
arr = np.array([1,9,3,6,8,7,5,2,0,3,6,4,1])
print(-np.sort(-arr))

[9 8 7 6 6 5 4 3 3 2 1 1 0]


### 1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность.

In [131]:
import numpy as np

matr = np.array([[0,3,9,5,6],[3,6,8,9,0],[3,3,4,7,5]])
print(matr)
print("Size: ",matr.size)
print("Shape: ", matr.shape)
print("Dimension: ", matr.ndim)

[[0 3 9 5 6]
 [3 6 8 9 0]
 [3 3 4 7 5]]
Size:  15
Shape:  (3, 5)
Dimension:  2


## 2. Библиотека Pandas
Первым шагом в любом начинании в области машинного обучения является введение исходных данных в систему. Исходные данные могут вводиться вручную, содержаться в файле или храниться в интернете в какомлибо формате. Кроме того, часто требуется получить данные из нескольких источников.

Библиотека pandas – это удобный и быстрый инструмент для работы с данными, обладающий большим функционалом. Если очень кратко, то pandas – это библиотека, которая предоставляет очень удобные с точки зрения использования инструменты для хранения данных и работе с ними.

Библиотека pandas присутствует в стандартной поставке Anaconda.

Если же ее там нет, то его можно установить отдельно. Для этого введите командной строке:
`pip install pandas`
Для импорта библиотеки используйте команду:
```python
import pandas as pd
```

Библиотека pandas предоставляет две ключевые структуры данных:
Series и DataFrame.
- Series – это одномерная структура данных, ее можно представить, как
таблицу с одной строкой. С Series можно работать как с обычным массивом
(обращаться по номеру индекса), и как с ассоциированным массивом, когда
можно использовать ключ для доступа к элементам данных.

- DataFrame – это двумерная структура. Идейно она очень похожа на
обычную таблицу, что выражается в способе ее создания и работе с ее
элементами

### 2.2.1 Пример
Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего).

In [3]:
import pandas as pd
import numpy as np
lst=[1,2,3,4,5]
d = {'a':1,'b':2,'c':3}
ndarr = np.arange(1,6)

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr,['a','b','c','d','e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


### 2.2.2 Пример
Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме).

In [5]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5],['a','b','c','d','e'])
s2 = pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s3[3:])

1
5
d    4
e    5
dtype: int32


### 2.2.3 Пример
Создайте новый фрейм данных.

In [6]:
import pandas as pd

dataframe = pd.DataFrame()
dataframe['Имя']=['Джеки Джексон','Стивен Стивенсон']
dataframe['Возраст']=[38,25]
dataframe['Водитель']=[True,False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

### 2.2.4 Пример
Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [14]:
import pandas as pd

url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

### 2.2.5 Пример
Пронализировать характеристики фрейма данных.

Одна из самых простых вещей, которые мы можем сделать после
загрузки данных, – это взглянуть на первые несколько строк с помощью
метода head. На последние строки можно посмотреть с помощью
функции tail. Мы также можем взглянуть на количество строк и
столбцов: dataframe.shape. Кроме того, используя метод describe, мы
можем получить описательную статистику для любых числовых
столбцов.

In [21]:
import pandas as pd

url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'

dataframe = pd.read_csv(url)


Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [38]:
dataframe.head(2)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1

In [39]:
dataframe.tail(3)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
539380      FL     609         SFO       MKE          5  1439     255      0
539381      UA      78         HNL       SFO          5  1439     313      1
539382      US    1442         LAX       PHL          5  1439     301      1

In [40]:
dataframe.shape

(539383, 8)

In [41]:
dataframe.describe()

Flight      DayOfWeek           Time         Length  \
count  539383.000000  539383.000000  539383.000000  539383.000000   
mean     2427.928630       3.929668     802.728963     132.202007   
std      2067.429837       1.914664     278.045911      70.117016   
min         1.000000       1.000000      10.000000       0.000000   
25%       712.000000       2.000000     565.000000      81.000000   
50%      1809.000000       4.000000     795.000000     115.000000   
75%      3745.000000       5.000000    1035.000000     162.000000   
max      7814.000000       7.000000    1439.000000     655.000000   

               Delay  
count  539383.000000  
mean        0.445442  
std         0.497015  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

### 2.2.6 Пример
Выберите индивидуальные данные или срезы фрейма данных.

In [22]:
import pandas as pd

url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'

dataframe = pd.read_csv(url)
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

### 2.2.7 Пример
Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.

In [24]:
import pandas as pd

url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'

dataframe = pd.read_csv(url)
dataframe[dataframe['PClass']=='1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

### 2.3.1 Задание
Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [34]:
import pandas as pd
import numpy as np

A = pd.Series([2,3,6,8])
B = pd.Series([0,62,6,9])
K = np.power(B-A,2)
distance = np.sqrt(np.sum(K))
print(distance)

59.04235767650204
59.04235767650204


### 2.3.2
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets).

In [37]:
import pandas as np

url = 'https://raw.githubusercontent.com/akmand/datasets/main/airlines.csv'

dataframe = pd.read_csv(url)
dataframe.head(10)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1
4      AS     108         ANC       SEA          3    30     202      0
5      CO    1094         LAX       IAH          3    30     181      1
6      DL    1768         LAX       MSP          3    30     220      0
7      DL    2722         PHX       DTW          3    30     228      0
8      DL    2606         SFO       MSP          3    35     216      1
9      AA    2538         LAS       ORD          3    40     200      1

### 2.3.3 Задание
Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

In [42]:
dataframe.head(2)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1

In [43]:
dataframe.tail(3)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
539380      FL     609         SFO       MKE          5  1439     255      0
539381      UA      78         HNL       SFO          5  1439     313      1
539382      US    1442         LAX       PHL          5  1439     301      1

In [44]:
dataframe.shape

(539383, 8)

In [59]:
dataframe.describe()

Flight      DayOfWeek           Time         Length  \
count  539383.000000  539383.000000  539383.000000  539383.000000   
mean     2427.928630       3.929668     802.728963     132.202007   
std      2067.429837       1.914664     278.045911      70.117016   
min         1.000000       1.000000      10.000000       0.000000   
25%       712.000000       2.000000     565.000000      81.000000   
50%      1809.000000       4.000000     795.000000     115.000000   
75%      3745.000000       5.000000    1035.000000     162.000000   
max      7814.000000       7.000000    1439.000000     655.000000   

               Delay  
count  539383.000000  
mean        0.445442  
std         0.497015  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

In [58]:
#Срез 100-150
dataframe_cut = dataframe
dataframe_cut.iloc[100:150]

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
100      9E    3998         TLH       ATL          3   338      68      0
101      9E    4196         TYS       ATL          3   340      57      0
102      CO     214         DFW       IAH          3   340      59      1
103      DL    2123         BOS       DTW          3   340     144      0
104      DL    2597         RIC       ATL          3   340     109      0
105      DL    2626         FLL       ATL          3   340     118      0
106      DL     684         AUS       ATL          3   340     134      0
107      EV    5583         CHA       ATL          3   340      47      0
108      MQ    4563         CMH       LGA          3   340     100      0
109      XE    2616         LRD       IAH          3   340      66      1
110      XE    3006         BRO       IAH          3   340      70      0
111      XE    3015         CRP       IAH          3   340      59      1
112      XE    5970         LAN       ORD          3   340      71      0
113      9E    3659         ALB       ATL          3   345     183      0
114      9E    3862         SAT       MEM          3   345     119      1
115      9E    3949         PVD       DTW          3   345     135      1
116      9E    4143         FWA       DTW          3   345      59      0
117      AA    1141         JFK       MIA          3   345     190      0
118      AA    1297         DFW       MIA          3   345     160      0
119      AA    2320         DFW       ORD          3   345     140      0
120      CO    1677         PHL       IAH          3   345     219      0
121      CO    1727         BWI       IAH          3   345     208      0
122      CO     240         AUS       IAH          3   345      55      0
123      CO     278         SAT       IAH          3   345      54      0
124      CO     633         LGA       IAH          3   345     235      0
125      DL    1095         OKC       ATL          3   345     127      0
126      DL    1112         PIT       ATL          3   345     131      1
127      DL    1506         LAX       DTW          3   345     270      0
128      DL    1580         SFO       DTW          3   345     270      0
129      DL    2320         PBI       ATL          3   345     113      0
130      DL    2481         ORF       ATL          3   345     120      0
131      DL    2710         DFW       ATL          3   345     132      0
132      DL    2939         DCA       ATL          3   345     120      1
133      EV    5142         AEX       ATL          3   345     119      0
134      EV    5218         SYR       ATL          3   345     158      0
135      EV    5233         BTR       ATL          3   345      97      0
136      EV    5362         SHV       ATL          3   345     123      1
137      EV    5501         VLD       ATL          3   345      62      0
138      OH    6264         BDL       CVG          3   345     133      0
139      OH    6549         MFE       MEM          3   345     118      0
140      OO    6407         FAT       SFO          3   345      45      0
141      OO    6647         BZN       DEN          3   345     107      0
142      OO    6925         PHX       LAX          3   345      85      0
143      OO    6964         RDM       PDX          3   345      58      0
144      US    1423         DCA       CLT          3   345      85      0
145      XE    2919         LFT       IAH          3   345      58      0
146      XE    5951         CAK       ORD          3   345      95      0
147      OO    6480         IPL       YUM          3   346      34      0
148      OO    6843         EAU       CWA          3   346      32      0
149      UA     756         SFO       DEN          3   348     158      0

In [76]:
#100 рейсов с задержкой
dataframe[dataframe['Delay'] > 0].head(100)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0        CO     269         SFO       IAH          3    15     205      1
1        US    1558         PHX       CLT          3    15     222      1
2        AA    2400         LAX       DFW          3    20     165      1
3        AA    2466         SFO       DFW          3    20     195      1
5        CO    1094         LAX       IAH          3    30     181      1
..      ...     ...         ...       ...        ...   ...     ...    ...
471      US      86         OMA       PHX          3   360     175      1
473      US     985         MSY       CLT          3   360     108      1
474      WN    1067         OAK       SAN          3   360      85      1
478      WN    1851         ONT       OAK          3   360      80      1
480      WN    2529         IND       DEN          3   360     185      1

[100 rows x 8 columns]

## 3 Работа с числовыми данными
Количественные данные что-то измеряют – будь то размер класса,
ежемесячные продажи или оценки учащихся. Естественным способом
представления этих величин является численным (например, 150 студентов,
$529 392 продаж).
Нормализация данных — это общепринятая задача предобработки в
машинном обучении. Многие алгоритмы предполагают, что все признаки
находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.
Существует множество способов нормализации значений признаков,
чтобы масштабировать их к единому диапазону и использовать в различных
моделях машинного обучения. В зависимости от используемой функции, их
можно разделить на 2 большие группы: линейные и нелинейные. При
нелинейной нормализации в расчетных соотношениях используются
функции логистической сигмоиды или гиперболического тангенса. В
линейной нормализации изменение переменных осуществляется
пропорционально, по линейному закону.
На практике наиболее распространены следующие методы
нормализации признаков:
- Минимакс – линейное преобразование данных в диапазоне [0..1], где
минимальное и максимальное масштабируемые значения
соответствуют 0 и 1 соответственно;
![Minimax](./imgs/minimax.png)
- Z-масштабирование данных на основе среднего значения и
стандартного отклонения: производят деление разницы между
переменной и средним значением на стандартное отклонение.
![Z-Scaling](./imgs/z-scaling.png)

При масштабировании данных мы будем использовать одну из
популярных библиотек машинного обучения Scikit-learn. Библиотека
содержит пакет sklearn.preprocessing, который предоставляет широкие
возможности для нормализации данных. Следует отметить, что в целом
алгоритмы обучения выигрывают от стандартизации набора данных.

### 3.2.1 Пример
Прошкалируйте числовой признак в диапазон между двумя значениями

In [84]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5],[-100.1],[0],[100.1],[900.9]])

minimax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_feature = minimax_scale.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

### 3.2.2 Задание
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [88]:
x = np.array([[-1000.1],[-200.2],[500.5],[600.6],[9000.9]])
scaler = preprocessing.StandardScaler()

standard = scaler.fit_transform(x)

standard


array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [87]:
print('Среднее: ', round(standard.mean()))
print('Стандартное отклонение: ',standard.std())

Среднее:  0
Стандартное отклонение:  1.0


# 3.2.3 Пример
Дан фрейм данных
```python
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
```
Необходимо масштабировать его числовые столбцы.

In [90]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({ 'A':[14.00,90.20,90.95,96.27,91.21],
                        'B':[103.02,107.26,110.35,114.23,114.68],
                        'C':['big','small','big','small','small']})
dfTest[['A','B']]=scaler.fit_transform(dfTest[['A','B']])
dfTest


A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

### 3.3.1 Задание
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [107]:
import pandas as pd
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'

dataframe = pd.read_csv(url)
feature = np.array(dataframe['sepal_length_cm']).reshape(-1,1)
scaler = preprocessing.MinMaxScaler()
feature_res = scaler.fit_transform(feature)
feature


array([[5.1],
       [4.9],
       [4.7],
       [4.6],
       [5. ],
       [5.4],
       [4.6],
       [5. ],
       [4.4],
       [4.9],
       [5.4],
       [4.8],
       [4.8],
       [4.3],
       [5.8],
       [5.7],
       [5.4],
       [5.1],
       [5.7],
       [5.1],
       [5.4],
       [5.1],
       [4.6],
       [5.1],
       [4.8],
       [5. ],
       [5. ],
       [5.2],
       [5.2],
       [4.7],
       [4.8],
       [5.4],
       [5.2],
       [5.5],
       [4.9],
       [5. ],
       [5.5],
       [4.9],
       [4.4],
       [5.1],
       [5. ],
       [4.5],
       [4.4],
       [5. ],
       [5.1],
       [4.8],
       [5.1],
       [4.6],
       [5.3],
       [5. ],
       [7. ],
       [6.4],
       [6.9],
       [5.5],
       [6.5],
       [5.7],
       [6.3],
       [4.9],
       [6.6],
       [5.2],
       [5. ],
       [5.9],
       [6. ],
       [6.1],
       [5.6],
       [6.7],
       [5.6],
       [5.8],
       [6.2],
       [5.6],
       [5.9],
      

In [108]:
scaler_st = preprocessing.StandardScaler()
feature = np.array(dataframe['sepal_width_cm']).reshape(-1,1)
feature_std = scaler_st.fit_transform(feature)
feature_std

array([[ 1.03205722],
       [-0.1249576 ],
       [ 0.33784833],
       [ 0.10644536],
       [ 1.26346019],
       [ 1.95766909],
       [ 0.80065426],
       [ 0.80065426],
       [-0.35636057],
       [ 0.10644536],
       [ 1.49486315],
       [ 0.80065426],
       [-0.1249576 ],
       [-0.1249576 ],
       [ 2.18907205],
       [ 3.11468391],
       [ 1.95766909],
       [ 1.03205722],
       [ 1.72626612],
       [ 1.72626612],
       [ 0.80065426],
       [ 1.49486315],
       [ 1.26346019],
       [ 0.56925129],
       [ 0.80065426],
       [-0.1249576 ],
       [ 0.80065426],
       [ 1.03205722],
       [ 0.80065426],
       [ 0.33784833],
       [ 0.10644536],
       [ 0.80065426],
       [ 2.42047502],
       [ 2.65187798],
       [ 0.10644536],
       [ 0.33784833],
       [ 1.03205722],
       [ 0.10644536],
       [-0.1249576 ],
       [ 0.80065426],
       [ 1.03205722],
       [-1.74477836],
       [ 0.33784833],
       [ 1.03205722],
       [ 1.72626612],
       [-0